<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="F_4BYTES_TO_DWORD" Id="{7a992823-ba96-4133-88d3-ae2cf2187dfc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_4BYTES_TO_DWORD : DWORD
VAR_INPUT
	BByte0		: BYTE;
	BByte1		: BYTE;
	BByte2		: BYTE;
	BByte3		: BYTE;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_4BYTES_TO_DWORD := BByte3 *16#1000000 + BByte2 *16#10000 + BByte1 *16#100 + BByte0;]]></ST>
    </Implementation>
    <LineIds Name="F_4BYTES_TO_DWORD">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>